### ISSUE TITLE
APIの仕様改善

### ISSUE THREAD

**Issue by Myoko1110** [tako0614/yurucommu-core#8]
**APIの仕様が劣悪なので、いくつか改善点を挙げておきます。
これはあくまで提案ですので、採用してもしなくても構いません。**

- URIはすべて小文字
URIは大文字小文字が混在していないものにしましょう。一般的にはすべて小文字です。
例）api/v1/friends/...
つまり "Friends" ではなく "friends" にしましょう。

- バージョン番号
APIの仕様を変更をする場合に備えてバージョン番号を含めることをおすすめします。
例）api/v1/...

- パラメータ
IDの指定などにはパスパラメータを使うほうが望ましいです。
例）api/v1/friends/<ID>
理由は、このIDは一意の情報を表すのに必要な情報であるからです。
"getFriendInfoById" とかまじで最悪です。これは関数名ですか??
逆に言うと、振り込みをしたい場合はクエリパラメータ(?query=aa みたいなやつ)を用いるべきです。

- URIには "addFriend" のような動詞ではなく名詞を使うようにしましょう。
（理由は、HTTPメゾッドで既に動詞が使われているからです。）
> GET ─ フレンドを取得
> POST ─ フレンド申請を送信
> DELETE ─ フレンドを削除

などのように使い分けるようにしましょう。

- 基本情報の他を参照するもの(?)は...
例）api/v1/friends/\<ID>/icon
のようにすると、何を表すものかが明確になります。

他にも [ここ](https://zenn.dev/arsaga/articles/4a72774b1c93d2) が参考になると思います。

追記）最終的に1つにまとめるって言ってますけど、それ相当めんどくさいですよ。

**Comment by tako0614** [comment]
このissueを参考にしてまだ不完全ですが改善しました。
webアプリ作るの初めてでわからなかったのでとてもためになりました。
ご指摘いただきありがとうございます。
